[versions]
agp = "8.13.0"
java = "21"
targetSdk = "36"
compileSdk = "36"
minSdk = "29"

kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
ktlint = "1.5.0"

activityCompose = "1.11.0"
androidx-hilt = "1.3.0"
compose = "2025.10.01"
core = "1.17.0"
coroutines = "1.10.2"
google-hilt = "2.57.2"
kotlinx-collections-immutable = "0.4.0"
kotlinx-datetime = "0.7.1-0.6.x-compat"
lifecycle-runtime = "2.9.4"
lifecycle-viewmodel-nav3 = "1.0.0-alpha04"
nav3-core = "1.0.0-rc01"
room = "2.8.3"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
testparameterinjector = "1.19"
paparazzi = "1.3.5"

spotless = "7.2.1"
lint-gradle = "1.0.0-alpha05"
detekt = "1.23.8"
dependency-graphs = "0.1.6"
kotlin-serialization = "2.2.21"

conventions = "1.0"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSize = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3-core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3-core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle-viewmodel-nav3" }
androidx-room = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-test = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
androidx-lint-gradle = { module = "androidx.lint:lint-gradle", version.ref = "lint-gradle" }
google-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "google-hilt" }
google-hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "google-hilt" }
google-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "google-hilt" }
google-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "google-hilt" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" }
kotlinx-coroutines-playservices = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
javax-inject = { group = "javax.inject", name = "javax.inject", version = "1" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
testParameterInjector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "testparameterinjector" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
composeCompiler-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
paparazzi-gradlePlugin = { group = "app.cash.paparazzi", name = "paparazzi-gradle-plugin", version.ref = "paparazzi" }

[plugins]
agp-application = { id = "com.android.application", version.ref = "agp" }
agp-library = { id = "com.android.library", version.ref = "agp" }
kgp-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kgp-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "google-hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
room = { id = "androidx.room", version.ref = "room" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization" }

android-lint = { id = "com.android.lint", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dependencyGraphs = { id = "io.github.adityabhaskar.dependencygraph", version.ref = "dependency-graphs" }

application = { id = "net.c306.conventions.application", version.ref = "conventions" }
library-android = { id = "net.c306.conventions.library.android", version.ref = "conventions" }
library-kotlin = { id = "net.c306.conventions.library.kotlin", version.ref = "conventions" }
compose-library = { id = "net.c306.conventions.compose.library", version.ref = "conventions" }
compose-application = { id = "net.c306.conventions.compose.application", version.ref = "conventions" }
hilt = { id = "net.c306.conventions.hilt", version.ref = "conventions" }